#ifndef OPIVM_OPCODES
#define OPIVM_OPCODES

#define OPC_EXIT 0
#define OPC_VMCALL 1
#define OPC_CONSTF 2
#define OPC_CONSTI 3
#define OPC_CONSTV 4
#define OPC_CONSTP 5
#define OPC_PUSHVARF 6
#define OPC_PUSHVARI 7
#define OPC_PUSHVARV 8
#define OPC_PUSHVARP 9
#define OPC_POP 10
#define OPC_SETVARF 11
#define OPC_SETVARI 12
#define OPC_SETVARV 13
#define OPC_SETVARP 14
#define OPC_GETPROP 15
#define OPC_SETPROP 16
#define OPC_METCALL 17
#define OPC_GETPROPV 18
#define OPC_SETPROPV 19
#define OPC_METCALLV 20
#define OPC_JUMP 21
#define OPC_IFJUMP 22
#define OPC_INITFOR 23
#define OPC_LOOP 24
#define OPC_I2F 25
#define OPC_F2I 26
#define OPC_VEC2P 27
#define OPC_P2VEC 28
#define OPC_LASTVEC 29
#define OPC_OP_ADDFF 30
#define OPC_OP_ADDII 31
#define OPC_OP_ADDVV 32
#define OPC_OP_ANDBB 33
#define OPC_OP_DIVFF 34
#define OPC_OP_DIVII 35
#define OPC_OP_DIVVF 36
#define OPC_OP_EQFF 37
#define OPC_OP_EQII 38
#define OPC_OP_EQVV 39
#define OPC_OP_GEFF 40
#define OPC_OP_GEII 41
#define OPC_OP_GTFF 42
#define OPC_OP_GTII 43
#define OPC_OP_LEFF 44
#define OPC_OP_LEII 45
#define OPC_OP_LTFF 46
#define OPC_OP_LTII 47
#define OPC_OP_MULFF 48
#define OPC_OP_MULII 49
#define OPC_OP_MULVF 50
#define OPC_OP_NEFF 51
#define OPC_OP_NEGF 52
#define OPC_OP_NEGI 53
#define OPC_OP_NEGV 54
#define OPC_OP_NEII 55
#define OPC_OP_NEVV 56
#define OPC_OP_NOTBB 57
#define OPC_OP_ORBB 58
#define OPC_OP_SUBFF 59
#define OPC_OP_SUBII 60
#define OPC_OP_SUBVV 61
#define OPC_OP_XORBB 62
#endif
